

export const THEMES = [
    { name: "light", value: "light" },
    { name: "dark", value: "dark" },
    { name: "cupcake", value: "cupcake" },
    { name: "bumblebee", value: "bumblebee" },
    { name: "emerald", value: "emerald" },
    { name: "corporate", value: "corporate" },
    { name: "synthwave", value: "synthwave" },
    { name: "retro", value: "retro" },
    { name: "cyberpunk", value: "cyberpunk" },
    { name: "valentine", value: "valentine" },
    { name: "halloween", value: "halloween" },
    { name: "garden", value: "garden" },
    { name: "forest", value: "forest" },
    { name: "aqua", value: "aqua" },
    { name: "lofi", value: "lofi" },
    { name: "pastel", value: "pastel" },
    { name: "fantasy", value: "fantasy" },
    { name: "wireframe", value: "wireframe" },
    { name: "black", value: "black" },
    { name: "luxury", value: "luxury" },
    { name: "dracula", value: "dracula" },
    { name: "cmyk", value: "cmyk" },
    { name: "autumn", value: "autumn" },
    { name: "business", value: "business" },
    { name: "acid", value: "acid" },
    { name: "lemonade", value: "lemonade" },
    { name: "night", value: "night" },
    { name: "coffee", value: "coffee" },
    { name: "winter", value: "winter" },
    { name: "dim", value: "dim" },
    { name: "nord", value: "nord" },
    { name: "sunset", value: "sunset" },
    { name: "caramellatte", value: "caramellatte" },
    { name: "abyss", value: "abyss" },
    { name: "silk", value: "silk" },
];
